import Head from 'next/head'
import TopBar from '../components/TopBar'
import NavBar from '../components/NavBar'
import Hero from '../components/Hero'
import Activities from '../components/Activities'
import Booking from '../components/Booking'
import Gallery from '../components/Gallery'
import Contact from '../components/Contact'
import Footer from '../components/Footer'


export default function Home() {
	return (
		<>
			<Head>
				<title>Weekaway Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			
			
			<TopBar />
			<NavBar />
			<Hero />
			<Activities />
			<Booking />
			<Gallery />
			<Contact/>
			<Footer/>
		
		</>
	)
}
